routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::post('/test1',['as'=>'etat1','uses'=>'Admin\EtatController@interventionsByEmploye']);
Route::get('/admin/etat/interventions_par_employe','Admin\EtatController@InterByEmpl')->name('admin.interventions_par_employe.index');

Route::post('/test2',['as'=>'etat2','uses'=>'Admin\EtatController@problemesResolus']);
Route::get('/admin/etat/prnr','Admin\EtatController@doc22')->name('admin.prnr.index');

Route::post('/test3',['as'=>'etat3','uses'=>'Admin\EtatController@interventionsByDepartement']);
Route::get('/admin/etat/intervention_par_departement','Admin\EtatController@InterByDept')->name('admin.intervention_par_departement.index');

Route::post('/test4',['as'=>'etat4','uses'=>'Admin\EtatController@interventionsByProbleme']);
Route::get('/admin/etat/interventions_par_problemes','Admin\EtatController@InterByProbleme')->name('admin.interventions_par_problemes.index');

Route::post('/test5',['as'=>'etat5','uses'=>'Admin\EtatController@interventionsByIntervenantByDept']);
Route::get('/admin/etat/intervention_par_intervenant_pour_departement','Admin\EtatController@InterByInterByDept')->name('admin.intervention_par_intervenant_pour_departement.index');

Route::post('/test6',['as'=>'etat6','uses'=>'Admin\EtatController@interventionsByProblemeByDept']);
Route::get('/admin/etat/intervention_par_probleme_departement','Admin\EtatController@InterByProbByDept')->name('admin.intervention_par_probleme_departement.index');

Route::post('/test7',['as'=>'etat7','uses'=>'Admin\EtatController@totaux']);
Route::get('/admin/etat/total_etats','Admin\EtatController@TotalEtat')->name('admin.total_etats.index');

Route::post('/test9',['as'=>'etat9','uses'=>'Admin\EtatController@interventionTotal']);
Route::get('/admin/etat/total_intervention_intervenant','Admin\EtatController@interventionTotal')->name('admin.total_intervention_intervenant.index');


Auth::routes();

//Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
//Route::post('password/reset', 'Auth\PasswordController@reset');


Route::get('/modify', 'HomeController@modify')->name('modify');
Route::post('/modifyValidation', 'HomeController@modifyValidation')->name('modifyValidation');


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/intervention/binder', 'InterventionController@binder');


Route::namespace('Alerte')->group(function (){
   // Route::resource('alerte','Admin\AlerteController');
});


Route::namespace('Admin')->group(function () {

    Route::get('/alerte/alerting', 'AlerteController@alerting');
    Route::post('/alerte/alerting', 'AlerteController@alerting');

    Route::get('/alerte/sendemail', 'AlerteController@sendemail');
    Route::post('/alerte/sendemail', 'AlerteController@sendemail');

    Route::get('/alerte/intervenir', 'AlerteController@intervenir');
    Route::post('/alerte/intervenir', 'AlerteController@intervenir');

    Route::get('/intervenant/pass', 'AlerteController@intervenir');
    Route::post('/intervenant/pass', 'AlerteController@intervenir');

    //Route::get('/admin/modify', 'AdminController@modify')->name('modify');
    //Route::post('/admin/modifyValidation', 'AdminController@modifyValidation')->name('modifyValidation');

    Route::get('/admin/profil','AdminController@index')->name('admin.profil');

    Route::get('/admin/etat/intervenants_par_interventions','EtatController@index')->name('admin.intervenants_par_interventions.index');
    Route::post('/admin/etat/intervenants_par_interventions','EtatController@create')->name('admin.intervenants_par_interventions.create');

    Route::get('/admin/etat/total_etats','TotalController@index')->name('admin.total_etats.index');
    Route::post('/admin/etat/total_etats','TotalController@create')->name('admin.total_etats.create');

    Route::get('/admin/etat','EtatController@create')->name('admin.etat.create');

    Route::get('/interventions/print/{data}',['as'=>'interventions.print','uses'=>'EtatController@print']);

    Route::resource('employe','EmployeController');

    Route::resource('intervenant','IntervenantController');

    Route::resource('intervention','InterventionController');

    Route::resource('probleme','ProblemeController');

    Route::resource('alerte','AlerteController');

    Route::resource('forum','ForumController');
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Alerte.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alerte extends Model
{
    protected $fillable = [
        'id','employe_id_alerte','titre_alerte','description_alerte','etat_alerte','users_id_alerte','date_alerte'
    ];
}

app/Http/Controllers/Admin/AlerteController.php
<?php
/**
 * @author Donatien ASSIH
 */

namespace App\Http\Controllers\Admin;

use App\Alerte;
use App\Mail\Email;
use App\Observation;
use App\Probleme;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Psy\Util\Json;

class AlerteController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */



//    public function index()
//    {
//        $user = Auth::user();
//        $alertes = Alerte::all();
//        return view('alerte.index', compact('alertes', 'user'));
//    }



    public function alerting()
    {
        $not_threat = Alerte::where('etat_alerte', false)->get();
        return Json::encode($not_threat);
    }

    public function index()
    {
        $user = Auth::user();
        if (isset($_GET['id'])){
            $id = $_GET['id'];
            $alerte = Alerte::query()->where('id',$id)->firstOrFail();
            $utilisateurs = User::query()->where('id',$alerte->employe_id_alerte)->firstOrFail();}
        //$alertes = Alerte::all();
        $alertes = Alerte::where('alertes.etat_alerte',false)->get();
        return view('alerte.index',compact('alertes','user','utilisateurs','alerte'));
    }

//    public function alerting(){
//
////        $not_threat = DB::table('alertes')
////            ->select(DB::raw('users.*,alertes.*'))
////            ->join('users','alertes.employe_id_alerte','=','users.id')
////            ->where('etat_alerte',false)
////            ->get();
//
//        $not_threat = DB::select('select *'. 'from alertes, users' .'where alertes.employe_id_alerte = users.id' . 'and etat_alerte = false');
//
//        return Json::encode($not_threat);
//    }


    public function intervenir()
    {
        if (isset($_GET['id'])) {
            $id = $_GET['id'];
            $alerte = Alerte::query()->where('id', $id)->firstOrFail();
            $utilisateurs = User::query()->where('id', $alerte->employe_id_alerte)->firstOrFail();

            $problemes = Probleme::all();
            $observations = Observation::all();
            $description = $alerte->description_alerte;
            $debut = $alerte->date_alerte;
            $alerte->etat_alerte = true;
            /*
             * TODO
             *
            */
            $alerte->save();
            return view('alerte.intervenir', compact('user', 'problemes', 'utilisateurs', 'observations', 'description','debut'));
        } else {
            dd('Can\'t intervenir');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        return view('alerte.create', compact('user'));
    }

    /*public function sendemail(Alerte $alerte)
    {
        $emails = User::query('email')->where('type', 1)->get();
        $tos[] = null;
        foreach ($emails as $oneemail){
            $tos[] = $oneemail->email;
        }

        $sender = User::where('id', $alerte->employe_id_alerte)->firstOrFail();
        $title = $sender->nom . " " . $sender->prenom . ": ITSSUES";
        $content = "$alerte->titre_alerte \n$alerte->description_alerte";
        $user_name = $sender->nom . " " . $sender->prenom;

        try {
            $data = [
                'email' => $sender->email,
                'name' => $user_name,
                'subject' => $title,
                'content' => $content,
            ];

            Mail::queue('alerte.email', $data, function ($tos,$message) use ($data) {
                $subject=$data['subject'];
                $message->from($data['email'],$data['name']);
                $message->to($tos);
                $message->subject($subject);
            });
        } catch (\Exception $exception) {
            dd($exception->getMessage());
        }
    }*/

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'titre_alerte' => 'required',
            'description_alerte' => 'required',
        ]);

        $user = Auth::user();

        $alerte = new Alerte();
        $alerte->employe_id_alerte = $user->id;
//         $alerte->employe_id_alerte = Auth::user();
        $alerte->titre_alerte = strtoupper($request->titre_alerte);
//        $alerte->titre_alerte = $request->probleme;
        $alerte->description_alerte = ucfirst($request->description_alerte);
        $alerte->date_alerte = Carbon::now();
        $alerte->etat_alerte = false;

        if ($alerte->save()) {
            $emails = User::query('email')->where('type', 1)->get();
            foreach ($emails as $oneemail){
                $tos[] = $oneemail['email'];
            }

            Mail::to($tos)->send(new Email($alerte));

            flash('Alerte ajouté avec succès');

            return redirect(route('alerte.index'));
        }

        return redirect(route('alerte.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $alerte = Alerte::query()->where('id', $id)->firstOrFail();
        return view('alerte.edit', compact('user', 'alerte'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'libelle' => 'required',
        ]);

        $e = Alerte::find($id);
        $e->libelle = ucfirst($request->libelle);
//        $e->description = $request->description;
        $e->save();

        flash('Problème mis à jour avec succès');
        return redirect(route('probleme.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/alerte/create.blade.php
@include('layouts.headerAdmin')

    <div class="row">
        <div class="col-lg-12">
            <h3 class="text-center">Emettre une alerte</h3>

            <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('alerte.store')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <label>Titre</label>
                    <input class="form-control" type="text" name="titre_alerte" required value="{{old('titre_alerte')}}">
                    @if ($errors->has('titre_alerte'))
                        <p class="text-danger">{{ $errors->first('titre_alerte') }}</p>
                    @endif
                </div>

                {{--<div class="form-group">--}}
                    {{--<label>Titre</label>--}}
                    {{--<select name="probleme" id="" class="form-control">--}}
                        {{--<option value="">Faites une sélection</option>--}}
                        {{--@foreach(\App\Probleme::all()->sortBy('libelle') as $r)--}}
                            {{--<option value="{{$r->id}}">{{$r->libelle}}</option>--}}
                        {{--@endforeach--}}
                    {{--</select>--}}
                    {{--@if ($errors->has('probleme'))--}}
                        {{--<p class="text-danger">{{ $errors->first('probleme') }}</p>--}}
                    {{--@endif--}}
                {{--</div>--}}


                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="description_alerte" id="" cols="30" rows="5">{{old('description_alerte')}}</textarea>
                    @if ($errors->has('description_alerte'))
                        <p class="text-danger">{{ $errors->first('description_alerte') }}</p>
                    @endif
                </div>

                <button type="submit" class="btn btn-primary">Valider</button>
            </form>
        </div>
    </div>
@include('layouts.footerAdmin')

resources/views/alerte/edit.blade.php
@include('layouts.headerAdmin')


<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Modification intervention</h3>

        <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('alerte.update', $alerte->idAlerte)}}" method="post">
            {{csrf_field()}}
            {{method_field('PUT')}}

            <div class="form-group">
                <label>Titre de l'alerte</label>
                <input type="text" name="title" value="{{$alerte->titre_alerte}}">
                @if ($errors->has('titre_alerte'))
                    <p class="text-danger">{{ $errors->first('titre_alerte') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Description de l'alerte</label>
                <textarea name="description" id="" cols="30" rows="5" class="form-control" >{{$alerte->description_alerte}}</textarea>
                @if ($errors->has('description_alerte'))
                <p class="text-danger">{{ $errors->first('description_alerte') }}</p>
                @endif
            </div>

            {{--<div class="form-group">--}}
                {{--<label for="">Date de début intervention</label>--}}
                {{--<input type="datetime-local" name="debut" class="form-control">--}}
                {{--@if ($errors->has('debut'))--}}
                    {{--<p class="text-danger">{{ $errors->first('debut') }}</p>--}}
                {{--@endif--}}
            {{--</div>--}}

            <a type="button" href="{{route('alerte.index')}}" class="btn btn-warning">Annuler</a>

            <button type="submit" class="btn btn-primary">Valider</button>

        </form>
    </div>
</div>

@include('layouts.footerAdmin')

resources/views/alerte/email.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
</head>
<body>
<h3>{{$alerte['titre_alerte']}}</h3>
<p>{{$alerte['description_alerte']}}</p>
</body>
</html>

resources/views/alerte/index.blade.php
{{--@include('layouts.headerAdmin')--}}
{{--<div class="row">--}}
    {{--<div class="col-lg-12">--}}
        {{--<div class="table-responsive">--}}
            {{--<h2>Liste des Alertes <a href="{{route('alerte.create')}}" class="btn btn-primary pull-right"> Nouvelle--}}
                    {{--alerte</a></h2>--}}
            {{--<table class="table table-bordered table-hover tablesorter">--}}
                {{--<thead>--}}
                {{--<tr>--}}
                    {{--<th>Titre <i class="fa fa-sort"></i></th>--}}
                    {{--<th>Description <i class="fa fa-sort"></i></th>--}}
                {{--</tr>--}}
                {{--</thead>--}}
                {{--<tbody>--}}
                {{--@foreach($alertes->sortBy('titre_alerte') as $r)--}}
                {{--<tr>--}}
                    {{--<td>{{$r->titre_alerte}}</td>--}}
                    {{--<td>{{$r->description_alerte}}</td>--}}
                    {{--<td>--}}
                        {{--<a href="{{route('alerte.edit',$r->idAlerte)}}">--}}
                            {{--<button class="btn btn-warning"><i class="zmdi zmdi-edit"></i></button>--}}
                        {{--</a>--}}
                    {{--</td>--}}

                {{--</tr>--}}
                {{--@endforeach--}}
                {{--</tbody>--}}
            {{--</table>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
{{--@include('layouts.footerAdmin')--}}


@include('layouts.headerAdmin')
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <h2>Liste des Alertes <a href="{{route('alerte.create')}}" class="btn btn-primary pull-right"> Nouvelle
                    alerte</a></h2>
            <table class="table table-bordered table-hover tablesorter">
                <thead>
                <tr>
                    <th>Date <i class="fa fa-sort"></i></th>
                    <th>Titre <i class="fa fa-sort"></i></th>
                    <th>Description <i class="fa fa-sort"></i></th>
                    <th>Etat <i class="fa fa-sort"></i></th>
                </tr>
                </thead>
                <tbody>

                @foreach($alertes->sortByDesc('date_alerte') as $r)

                    @if ($r->etat_alerte==0)
                        <tr class="clickable-row" data-href="http://10.1.165.16/itissues/public/alerte/intervenir?id={{$r->id}}">
                            <td><b>{{\Carbon\Carbon::parse($r->date_alerte)->format('d/m/Y H:i:s')}}</b></td>
                            <td>{{$r->titre_alerte}}</td>
                            <td>{{$r->description_alerte}}</td>
                            <td class="alert alert-danger">{{'En attente'}}</td>
                        </tr>
                    @endif

                    @if ($r->etat_alerte==1)
                        <tr>
                            <td><b>{{\Carbon\Carbon::parse($r->date_alerte)->format('d/m/Y H:i:s')}}</b></td>
                            <td>{{$r->titre_alerte}}</td>
                            <td>{{$r->description_alerte}}</td>
                            <td class="alert alert-success">{{'Traité'}}</td>
                        </tr>
                    @endif

                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('layouts.footerAdmin')
<script>
    $(".clickable-row").click(function () {
        window.location = $(this).data("href");
    });
</script>

resources/views/alerte/intervenir.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Nouvelle intervention</h3>

        <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('intervention.store')}}" method="post">
            {{csrf_field()}}

            <div class="form-group">
                <label>Utilisateur</label>
                <select name="employe" id="" class="form-control">
                    <option value="<?=$utilisateurs->id?>"><?=$utilisateurs->nom." ".$utilisateurs->prenom?></option>
                </select>
                @if ($errors->has('employe'))
                <p class="text-danger">{{ $errors->first('employe') }}</p>
                @endif
            </div>
            <div class="form-group">
                <label>Problème</label>
                <select name="probleme" id="" class="form-control">
                    <option value="">Sélectionnez un problème</option>
                    @foreach($problemes->sortBy('libelle') as $r)
                    <option value="{{$r->id}}">{{$r->libelle}}</option>
                    @endforeach
                </select>
                @if ($errors->has('probleme'))
                <p class="text-danger">{{ $errors->first('probleme') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Description du Problème</label>
                <textarea name="descriptionPro" id="" cols="30" rows="5" class="form-control">{{$description}}</textarea>
                @if ($errors->has('descriptionPro'))
                <p class="text-danger">{{ $errors->first('descriptionPro') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Description de la résolution</label>
                <textarea name="description" id="" cols="30" rows="5" class="form-control"></textarea>
                @if ($errors->has('description'))
                    <p class="text-danger">{{ $errors->first('description') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Observations</label>
                <select name="observation" id="" class="form-control">
                    <option value="">Sélectionnez une observation</option>
                    @foreach($observations as $r)
                    <option value="{{$r->id}}">{{$r->libelleObservation}}</option>
                    @endforeach
                </select>
                @if ($errors->has('observation'))
                <p class="text-danger">{{ $errors->first('observation') }}</p>
                @endif
            </div>

            {{--<div class="form-group">--}}
                {{--<label for="">Date de début intervention</label>--}}
                {{--<input type="datetime-local" name="debut" class="form-control">--}}
                {{--@if ($errors->has('debut'))--}}
                {{--<p class="text-danger">{{ $errors->first('debut') }}</p>--}}
                {{--@endif--}}
            {{--</div>--}}

            <div class="form-group">
                <label for="">Date de début intervention</label>
                <input type="datetime-local" name="debut" class="form-control" value="{{$debut}}">
                @if ($errors->has('debut'))
                    <p class="text-danger">{{ $errors->first('debut') }}</p>
                @endif
            </div>



            <div class="form-group">
                <label for="">Date de fin intervention</label>
                <input type="datetime-local" name="fin" class="form-control">
                @if ($errors->has('fin'))
                    <p class="text-danger">{{ $errors->first('fin') }}</p>
                @endif
            </div>


            <div class="form-group">
                <input type="hidden" name="intervenir-name" class="form-control" value="<?=$utilisateurs->nom?>">
                <input type="hidden" name="intervenir-surname" class="form-control" value="<?=$utilisateurs->prenom?>">
            </div>

            {{--<div class="form-group">--}}
                {{--<label for="">Durée de l'intervention</label>--}}
                {{--<input type="text" name="duration1" class="form-control">--}}
                {{--@if ($errors->has('duration1'))--}}
                    {{--<p class="text-danger">{{ $errors->first('duration1') }}</p>--}}
                {{--@endif--}}
            {{--</div>--}}

            <button type="submit" class="btn btn-primary">Valider</button>
        </form>
    </div>
</div>

@include('layouts.footerAdmin')