routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::post('/test1',['as'=>'etat1','uses'=>'Admin\EtatController@interventionsByEmploye']);
Route::get('/admin/etat/interventions_par_employe','Admin\EtatController@InterByEmpl')->name('admin.interventions_par_employe.index');

Route::post('/test2',['as'=>'etat2','uses'=>'Admin\EtatController@problemesResolus']);
Route::get('/admin/etat/prnr','Admin\EtatController@doc22')->name('admin.prnr.index');

Route::post('/test3',['as'=>'etat3','uses'=>'Admin\EtatController@interventionsByDepartement']);
Route::get('/admin/etat/intervention_par_departement','Admin\EtatController@InterByDept')->name('admin.intervention_par_departement.index');

Route::post('/test4',['as'=>'etat4','uses'=>'Admin\EtatController@interventionsByProbleme']);
Route::get('/admin/etat/interventions_par_problemes','Admin\EtatController@InterByProbleme')->name('admin.interventions_par_problemes.index');

Route::post('/test5',['as'=>'etat5','uses'=>'Admin\EtatController@interventionsByIntervenantByDept']);
Route::get('/admin/etat/intervention_par_intervenant_pour_departement','Admin\EtatController@InterByInterByDept')->name('admin.intervention_par_intervenant_pour_departement.index');

Route::post('/test6',['as'=>'etat6','uses'=>'Admin\EtatController@interventionsByProblemeByDept']);
Route::get('/admin/etat/intervention_par_probleme_departement','Admin\EtatController@InterByProbByDept')->name('admin.intervention_par_probleme_departement.index');

Route::post('/test7',['as'=>'etat7','uses'=>'Admin\EtatController@totaux']);
Route::get('/admin/etat/total_etats','Admin\EtatController@TotalEtat')->name('admin.total_etats.index');

Route::post('/test9',['as'=>'etat9','uses'=>'Admin\EtatController@interventionTotal']);
Route::get('/admin/etat/total_intervention_intervenant','Admin\EtatController@interventionTotal')->name('admin.total_intervention_intervenant.index');


Auth::routes();

//Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
//Route::post('password/reset', 'Auth\PasswordController@reset');


Route::get('/modify', 'HomeController@modify')->name('modify');
Route::post('/modifyValidation', 'HomeController@modifyValidation')->name('modifyValidation');


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/intervention/binder', 'InterventionController@binder');


Route::namespace('Alerte')->group(function (){
   // Route::resource('alerte','Admin\AlerteController');
});


Route::namespace('Admin')->group(function () {

    Route::get('/alerte/alerting', 'AlerteController@alerting');
    Route::post('/alerte/alerting', 'AlerteController@alerting');

    Route::get('/alerte/sendemail', 'AlerteController@sendemail');
    Route::post('/alerte/sendemail', 'AlerteController@sendemail');

    Route::get('/alerte/intervenir', 'AlerteController@intervenir');
    Route::post('/alerte/intervenir', 'AlerteController@intervenir');

    Route::get('/intervenant/pass', 'AlerteController@intervenir');
    Route::post('/intervenant/pass', 'AlerteController@intervenir');

    //Route::get('/admin/modify', 'AdminController@modify')->name('modify');
    //Route::post('/admin/modifyValidation', 'AdminController@modifyValidation')->name('modifyValidation');

    Route::get('/admin/profil','AdminController@index')->name('admin.profil');

    Route::get('/admin/etat/intervenants_par_interventions','EtatController@index')->name('admin.intervenants_par_interventions.index');
    Route::post('/admin/etat/intervenants_par_interventions','EtatController@create')->name('admin.intervenants_par_interventions.create');

    Route::get('/admin/etat/total_etats','TotalController@index')->name('admin.total_etats.index');
    Route::post('/admin/etat/total_etats','TotalController@create')->name('admin.total_etats.create');

    Route::get('/admin/etat','EtatController@create')->name('admin.etat.create');

    Route::get('/interventions/print/{data}',['as'=>'interventions.print','uses'=>'EtatController@print']);

    Route::resource('employe','EmployeController');

    Route::resource('intervenant','IntervenantController');

    Route::resource('intervention','InterventionController');

    Route::resource('probleme','ProblemeController');

    Route::resource('alerte','AlerteController');

    Route::resource('forum','ForumController');
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Probleme.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Probleme extends Model
{
    protected $fillable = [
        'libelle','description','date_debut','date_fin'
    ];
}

app/Http/Controllers/Admin/ProblemeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Probleme;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProblemeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $problemes = Probleme::all();
        return view('admin.problemes.index',compact('problemes','user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        return view('admin.problemes.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'libelle'=>'required',
//            'description'=>'required',
        ]);

        $e = new Probleme();
        $e->libelle = strtoupper($request->libelle);
//        $e->description = $request->description;
        $e->save();

        flash('Problème ajouté avec succès');
        return redirect(route('probleme.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $probleme = Probleme::find($id);
        return view('admin.problemes.edit',compact('user','probleme'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'libelle'=>'required',
        ]);

        $e = Probleme::find($id);
        $e->libelle= strtoupper($request->libelle);
//        $e->description = $request->description;
        $e->save();

        flash('Problème mis à jour avec succès');
        return redirect(route('probleme.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/problemes/create.blade.php
@include('layouts.headerAdmin')

    <div class="row">
        <div class="col-lg-12">
            <h3 class="text-center">Enrégister un nouveau problème</h3>

            <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('probleme.store')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <label>Libelle</label>
                    <input class="form-control" type="text" name="libelle" required value="{{old('libelle')}}">
                    @if ($errors->has('libelle'))
                        <p class="text-danger">{{ $errors->first('libelle') }}</p>
                    @endif
                </div>

                {{--<div class="form-group">--}}
                    {{--<label>Description</label>--}}
                    {{--<textarea class="form-control" name="description" id="" cols="30" rows="5">{{old('description')}}</textarea>--}}
                    {{--@if ($errors->has('description'))--}}
                        {{--<p class="text-danger">{{ $errors->first('description') }}</p>--}}
                    {{--@endif--}}
                {{--</div>--}}

                <button type="submit" class="btn btn-primary">Valider</button>
            </form>
        </div>
    </div>
@include('layouts.footerAdmin')

resources/views/admin/problemes/edit.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Modification du problème</h3>
            <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('probleme.update',$probleme->id)}}" method="post">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="form-group">
                    <label>Libellé</label>
                    <input class="form-control" type="text" name="libelle" required value="{{$probleme->libelle}}">
                    @if ($errors->has('libelle'))
                        <p class="text-danger">{{ $errors->first('libelle') }}</p>
                    @endif
                </div>

                {{--<div class="form-group">--}}
                    {{--<label>Description</label>--}}
                    {{--<textarea class="form-control" required name="description" cols="30" rows="10">{{$probleme->description}}</textarea>--}}
                    {{--@if ($errors->has('description'))--}}
                        {{--<p class="text-danger">{{ $errors->first('description') }}</p>--}}
                    {{--@endif--}}
                {{--</div>--}}

                <a type="button" href="{{route('probleme.index')}}" class="btn btn-warning">Annuler</a>

                <button type="submit" class="btn btn-primary">Valider</button>
            </form>
        </div>
    </div>

@include('layouts.footerAdmin')

resources/views/admin/problemes/index.blade.php
@include('layouts.headerAdmin')

    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <h2>Liste des Problèmes <a href="{{route('probleme.create')}}" class="btn btn-primary pull-right"> Nouveau problème</a>  </h2>
                <table class="table table-bordered table-hover tablesorter">
                    <thead>
                    <tr>
                        <th>Libellé <i class="fa fa-sort"></i></th>
                        <th>Description <i class="fa fa-sort"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($problemes->sortBy('libelle') as $r)
                        <tr>
                            <td>{{$r->libelle}}</td>
                            {{--<td>{{$r->descriptionPro}}</td>--}}
                            <td>
                                <a href="{{route('probleme.edit',$r->id)}}">
                                    <button class="btn btn-warning" > <i class="zmdi zmdi-edit"></i></button>
                                </a>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@include('layouts.footerAdmin')