routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::post('/test1',['as'=>'etat1','uses'=>'Admin\EtatController@interventionsByEmploye']);
Route::get('/admin/etat/interventions_par_employe','Admin\EtatController@InterByEmpl')->name('admin.interventions_par_employe.index');

Route::post('/test2',['as'=>'etat2','uses'=>'Admin\EtatController@problemesResolus']);
Route::get('/admin/etat/prnr','Admin\EtatController@doc22')->name('admin.prnr.index');

Route::post('/test3',['as'=>'etat3','uses'=>'Admin\EtatController@interventionsByDepartement']);
Route::get('/admin/etat/intervention_par_departement','Admin\EtatController@InterByDept')->name('admin.intervention_par_departement.index');

Route::post('/test4',['as'=>'etat4','uses'=>'Admin\EtatController@interventionsByProbleme']);
Route::get('/admin/etat/interventions_par_problemes','Admin\EtatController@InterByProbleme')->name('admin.interventions_par_problemes.index');

Route::post('/test5',['as'=>'etat5','uses'=>'Admin\EtatController@interventionsByIntervenantByDept']);
Route::get('/admin/etat/intervention_par_intervenant_pour_departement','Admin\EtatController@InterByInterByDept')->name('admin.intervention_par_intervenant_pour_departement.index');

Route::post('/test6',['as'=>'etat6','uses'=>'Admin\EtatController@interventionsByProblemeByDept']);
Route::get('/admin/etat/intervention_par_probleme_departement','Admin\EtatController@InterByProbByDept')->name('admin.intervention_par_probleme_departement.index');

Route::post('/test7',['as'=>'etat7','uses'=>'Admin\EtatController@totaux']);
Route::get('/admin/etat/total_etats','Admin\EtatController@TotalEtat')->name('admin.total_etats.index');

Route::post('/test9',['as'=>'etat9','uses'=>'Admin\EtatController@interventionTotal']);
Route::get('/admin/etat/total_intervention_intervenant','Admin\EtatController@interventionTotal')->name('admin.total_intervention_intervenant.index');


Auth::routes();

//Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
//Route::post('password/reset', 'Auth\PasswordController@reset');


Route::get('/modify', 'HomeController@modify')->name('modify');
Route::post('/modifyValidation', 'HomeController@modifyValidation')->name('modifyValidation');


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/intervention/binder', 'InterventionController@binder');


Route::namespace('Alerte')->group(function (){
   // Route::resource('alerte','Admin\AlerteController');
});


Route::namespace('Admin')->group(function () {

    Route::get('/alerte/alerting', 'AlerteController@alerting');
    Route::post('/alerte/alerting', 'AlerteController@alerting');

    Route::get('/alerte/sendemail', 'AlerteController@sendemail');
    Route::post('/alerte/sendemail', 'AlerteController@sendemail');

    Route::get('/alerte/intervenir', 'AlerteController@intervenir');
    Route::post('/alerte/intervenir', 'AlerteController@intervenir');

    Route::get('/intervenant/pass', 'AlerteController@intervenir');
    Route::post('/intervenant/pass', 'AlerteController@intervenir');

    //Route::get('/admin/modify', 'AdminController@modify')->name('modify');
    //Route::post('/admin/modifyValidation', 'AdminController@modifyValidation')->name('modifyValidation');

    Route::get('/admin/profil','AdminController@index')->name('admin.profil');

    Route::get('/admin/etat/intervenants_par_interventions','EtatController@index')->name('admin.intervenants_par_interventions.index');
    Route::post('/admin/etat/intervenants_par_interventions','EtatController@create')->name('admin.intervenants_par_interventions.create');

    Route::get('/admin/etat/total_etats','TotalController@index')->name('admin.total_etats.index');
    Route::post('/admin/etat/total_etats','TotalController@create')->name('admin.total_etats.create');

    Route::get('/admin/etat','EtatController@create')->name('admin.etat.create');

    Route::get('/interventions/print/{data}',['as'=>'interventions.print','uses'=>'EtatController@print']);

    Route::resource('employe','EmployeController');

    Route::resource('intervenant','IntervenantController');

    Route::resource('intervention','InterventionController');

    Route::resource('probleme','ProblemeController');

    Route::resource('alerte','AlerteController');

    Route::resource('forum','ForumController');
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Intervention.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Intervention extends Model
{

    protected $fillable = [
        'description','user_id','probleme_id','employe_id','debut','fin','duration1'
    ];

    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }

    public function employe()
    {
        return $this->belongsTo('App\Employe','employe_id');
    }

    public function probleme()
    {
        return $this->belongsTo('App\Probleme','probleme_id');
    }

    public function observation()
    {
        return $this->belongsTo('App\Observation','observation_id');
    }

}

app/Http/Controllers/Admin/InterventionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Employe;
use App\Intervention;
use App\Observation;
use App\Probleme;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class InterventionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        $intervention = Intervention::all();
        $interventions = Intervention::with(['employe','probleme','observation','user'])->orderByDesc('fin')->paginate(10);

        foreach ($interventions as $oneIntervention){

            $formatt = explode('-',$oneIntervention->duration1);
            if (count($formatt)>=3 ){
                $formatte = explode(' ',$formatt[2]);
                //dd($formatt);

                $oneIntervention->duration1 = $formatt[0].'-'.(str_pad($formatt[1]-1,2,'0',STR_PAD_LEFT)).'-'.(str_pad($formatte[0]-1,2,'0',STR_PAD_LEFT)).' '.($formatte[1]);
            }
        }

        if ($request->ajax()){
            return DataTables::of($intervention)->make(true);
        }

        return view('admin.interventions.index',compact('interventions','intervention','user'));
    }

    /**
     * @return mixed
     * @throws \Exception
     */
    public function binder(){
        return DataTables::of(Intervention::query())->make(true);
    }

    public function alertecreate($id){
        $user = Auth::user();
        $employes = Employe::all();
        $problemes = Probleme::all();
        $observations = Observation::all();

        return view('admin.interventions.create', compact('user','problemes','employes','observations'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $employes = Employe::all();
        $problemes = Probleme::all();
        $observations = Observation::all();
        return view('admin.interventions.create',compact('user','problemes','employes','observations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \DateTime $datedebut
     * @param \DateTime $datefin
     * @param null $param
     * @return string
     */

    public static function dur(\DateTime $datedebut, \DateTime $datefin, $param = null){
        $temps = $datedebut->diff($datefin, true);
        /**
         * valeur possible de $param attendu
         *
         * %Y en année
         * %m en mois
         * %d en jours
         * %H en heures
         * %i en minutes
         * %s en secondes
         *
         */
        if ($param != null){
            return $temps->format($param);
        }else{
            return $temps->format('%m mois %d jrs  %H H %i min %s s');
        }

    }


//    /**
//     * @param string $date
//     * @param string $duration
//     * @return string
//     * @throws \Exception
//     */
//    public function durationSum($date,$duration){
//
//        //la duration est en minute;
//       // $dateInterval = 'PT'.$duration.'M';
//
//        /**
//        si la duration est en date exemple 01:35:00
//         * decommenter ce bloc et commenter celui de dessus
//         */
//        $duration = new DateTime($duration);
//        $duration_year = $duration->format('Y').'Y';
//        $duration_month = 1-$duration->format('m').'M';
//        $duration_day = 1-$duration->format('d').'D';
//        $duration_hour = $duration->format('H').'H';
//        $duration_min = $duration->format('i').'M';
//        $duration_second = $duration->format('s').'S';
//
//        $dateInterval = 'P'.$duration_year.$duration_month.$duration_day.'T'.$duration_hour.$duration_min.$duration_second;
//
//
//        $date = new DateTime($date);
//        $date->add(new DateInterval($dateInterval));
//        return $date->format('Y-m-d H:i:s') . "\n";
//    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'employe'=>'required',
            'probleme'=>'required',
            'description'=>'required',
            'observation'=>'required',
      ]);

        $e = new Intervention();
        $e->user_id = Auth::id();

        if (isset($_POST['intervenir-name'],$_POST['intervenir-surname']) && !empty($_POST['intervenir-name']) && !empty($_POST['intervenir-surname'])){
            $intervenir_name =  $_POST['intervenir-name'];
            $intervenir_surname =  $_POST['intervenir-surname'];

            $employe = Employe::query()->where('nomEmp',$intervenir_name)
                                        ->where('prenomEmp',$intervenir_surname)->firstOrFail();
            $e->employe_id = $employe->id;
        }else{
            $e->employe_id = $request->employe;
        }


        $e->probleme_id = $request->probleme;
        $e->observation_id = $request->observation;
        $e->descriptionPro = ucfirst($request->descriptionPro);
        $e->description = ucfirst($request->description);
        $e->debut = new Carbon($request->input('debut'));
        $e->fin = new  Carbon($request->input('fin'));
        $e->duree = self::dur($e->debut,$e->fin,null);

        //$formatt = explode('-',$request->duration1);
        //$formatte = explode(' ',$formatt[2]);
        //dd($formatte);

       // $e->duration1 = $formatt[0].'-'.(str_pad($formatt[1]+1,2,'0',STR_PAD_LEFT)).'-'.(str_pad($formatte[0]+1,2,'0',STR_PAD_LEFT)).' '.($formatte[1]);

//        $e->fin = self::durationSum($e->debut,$e->duration1);
        $e->save();


        flash('Intervention enrégistée avec succès');
        return redirect(route('intervention.index'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function edit($id)
    {
        $user = Auth::user();
        $intervention = Intervention::find($id);
        $problemes = Probleme::all();
        $employes = Employe::all();
        $observations = Observation::all();
        return view('admin.interventions.edit',compact('user','intervention','problemes','employes','observations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'description'=>'required',
            'observation'=>'required',
        ]);

        $e = Intervention::find($id);
        $e->observation_id = $request->observation;
        $e->descriptionPro = ucfirst($request->descriptionPro);
        $e->description = ucfirst($request->description);

        $e->save();

        flash('Intervention modifiée avec succès');
        return redirect(route('intervention.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/interventions/create.blade.php
@include('layouts.headerAdmin')


    <div class="container">
        <div class="col-sm-12">
            <h3 class="text-center">Nouvelle intervention</h3>
        <br>
        <br>
        <br>

            <form class="col-sm-12" action="{{route('intervention.store')}}" method="post">
                {{csrf_field()}}

                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Employé</label>
                        <select name="employe" id="" class="form-control">
                            <option value="">Sélectionnez un employé</option>
                            @foreach(\App\Employe::all()->sortBy('nomEmp') as $r)
                                <option value="{{$r->id}}">{{$r->nomEmp." ".$r->prenomEmp}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('employe'))
                            <p class="text-danger">{{ $errors->first('employe') }}</p>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Activité ou problème</label>
                        <select name="probleme" id="" class="form-control">
                            <option value="">Faites une sélection</option>
                            @foreach(\App\Probleme::all()->sortBy('libelle') as $r)
                                <option value="{{$r->id}}">{{$r->libelle}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('probleme'))
                            <p class="text-danger">{{ $errors->first('probleme') }}</p>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="descriptionPro">Description du problème ou l'activité</label>
                        <textarea name="descriptionPro" id="" cols="30" rows="5" class="form-control"></textarea>
                        @if ($errors->has('descriptionPro'))
                            <p class="text-danger">{{ $errors->first('descriptionPro') }}</p>
                        @endif
                    </div>

                </div>
                <div class="col-sm-6">
                    <div class="col-sm">
                        <label>Description de l'action effectuée</label>
                        <textarea name="description" id="" cols="30" rows="5" class="form-control"></textarea>
                        @if ($errors->has('description'))
                            <p class="text-danger">{{ $errors->first('description') }}</p>
                        @endif
                    </div>

                    <div class="col-sm">
                        <label>Observations</label>
                        <select name="observation" id="" class="form-control">
                            <option value="">Sélectionnez une observation</option>
                            @foreach(\App\Observation::all() as $r)
                                <option value="{{$r->id}}">{{$r->libelleObservation}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('observation'))
                            <p class="text-danger">{{ $errors->first('observation') }}</p>
                        @endif
                    </div>

                    <div class="col-sm">
                        <label for="debut">Date de début intervention</label>
                        <input type="datetime-local" name="debut" class="form-control">
                        @if ($errors->has('debut'))
                            <p class="text-danger">{{ $errors->first('debut') }}</p>
                        @endif
                    </div>


                    <div class="col-sm">
                        <label for="">Date de fin intervention</label>
                        <input type="datetime-local" name="fin" class="form-control">
                        @if ($errors->has('fin'))
                            <p class="text-danger">{{ $errors->first('fin') }}</p>
                        @endif
                    </div>
                </div>

                <HR />
                <button type="submit" class="col-sm-push btn btn-primary text-center">Valider</button>
            </form>

        </div>
    </div>

@include('layouts.footerAdmin')

resources/views/admin/interventions/edit.blade.php
@include('layouts.headerAdmin')


<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Modification intervention</h3>

        <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('intervention.update', $intervention->id)}}" method="post">
            {{csrf_field()}}
            {{method_field('PUT')}}

            <div class="form-group">
                <label>Description du problème</label>
                <textarea name="descriptionPro" id="" cols="20" rows="3" class="form-control" >{{$intervention->descriptionPro}}</textarea>
                @if ($errors->has('descriptionPro'))
                    <p class="text-danger">{{ $errors->first('descriptionPro') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Description de la résolution</label>
                <textarea name="description" id="" cols="30" rows="5" class="form-control" >{{$intervention->description}}</textarea>
                @if ($errors->has('description'))
                    <p class="text-danger">{{ $errors->first('description') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Observations</label>
                <select name="observation" id="" class="form-control">
                    <option value="">Sélectionnez une observation</option>
                    @foreach(\App\Observation::all() as $r)
                        <option value="{{$r->id}}">{{$r->libelleObservation}}</option>
                    @endforeach
                </select>
                @if ($errors->has('observation'))
                    <p class="text-danger">{{ $errors->first('observation') }}</p>
                @endif
            </div>

            {{--<div class="form-group">--}}
                {{--<label for="">Date de début intervention</label>--}}
                {{--<input type="datetime-local" name="debut" class="form-control">--}}
                {{--@if ($errors->has('debut'))--}}
                    {{--<p class="text-danger">{{ $errors->first('debut') }}</p>--}}
                {{--@endif--}}
            {{--</div>--}}

            <a type="button" href="{{route('intervention.index')}}" class="btn btn-warning">Annuler</a>

            <button type="submit" class="btn btn-primary">Valider</button>

        </form>
    </div>
</div>

@include('layouts.footerAdmin')

resources/views/admin/interventions/index.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive data-table_filter">
            <h2>Liste des Interventions <a href="{{route('intervention.create')}}" class="btn btn-primary pull-right">
                    <i class="zmdi zmdi-plus"></i>
                    Nouvelle intervention</a>
            </h2>
            <table id="table" class="table table-responsive table-striped table-wrapper-scroll-y table-bordered table-hover datatable" width="100%">
                <thead>
                <tr role="row">
                    <th class="th-sm sorting"><b>Intervenants</b></th>
                    <th class="th-sm sorting"><b>Employés</b> </th>
                    <th class="th-sm sorting"><b>Problèmes ou Activités</b> </th>
                    <th class="th-sm sorting"><b>Description du problème </b></th>
                    <th class="th-sm sorting"><b>Description de la résolution</b></th>
                    <th class="th-sm sorting"><b>Observations</b> </th>
                    <th class="th-sm sorting"><b>Début</b> </th>
                    <th class="th-sm sorting"><b>Fin</b> </th>
                    <th class="th-sm sorting"><b>Durée</b> </th>
                    <th class="th-sm sorting"><b>Duration</b> </th>
                </tr>
                </thead>
              <tbody>
                @foreach($interventions as $e)
                    <tr>
                        <td>{{$e->user->nom." ".$e->user->prenom}}</td>
                        <td>{{$e->employe->nomEmp." ".$e->employe->prenomEmp}}</td>
                        <td>{{$e->probleme->libelle}}</td>
                        <td>{{$e->descriptionPro}}</td>
                        <td>{{$e->description}}</td>
                        <td>{{$e->observation->libelleObservation}}</td>
                        <td><b>{{\Carbon\Carbon::parse($e->debut)->format('d/m/Y H:i:s')}}</b></td>
                        <td><b>{{\Carbon\Carbon::parse($e->fin)->format('d/m/Y H:i:s')}}</b></td>
                        <td><b>{{$e->duree}}</b></td>
                        <td><b>{{$e->duration1}}</b></td>
                        <td>
                            <a href="{{route('intervention.edit',$e->id)}}">
                                <button class="btn btn-warning" > <i class="zmdi zmdi-edit"></i></button>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="th-sm">Intervenants</th>
                    <th class="th-sm">Employés </th>
                    <th class="th-sm">Problèmes </th>
                    <th class="th-sm">Description du problème</th>
                    <th class="th-sm">Description de la résolution</th>
                    <th class="th-sm">Observations </th>
                    <th class="th-sm">Début </th>
                    <th class="th-sm">Fin </th>
                    <th class="th-sm">duree </th>
                    <th class="th-sm">duration </th>
                </tr>
                </tfoot>
            </table>
          <center> <?= $interventions->render() ?></center>
        </div>
    </div>
</div>

@include('layouts.footerAdmin')

{{--@section('script')--}}
    {{--<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>--}}
    {{--<script type="text/javascript">--}}
        {{--$(document).ready(function() {--}}
            {{--$('#table').DataTable({--}}
                {{--processing: true,--}}
                {{--serverSide: true,--}}
                {{--ajax: '{{ route('binder') }}',--}}
                {{--columns: [--}}
                    {{--{ data: 'nomEmp', name: 'nomEmp' },--}}
                    {{--{ data: 'prenomEmp', name: 'prenomEmp' },--}}
                    {{--{ data: 'prenom', name: 'prenom' },--}}
                    {{--{ data: 'nom', name: 'nom' }--}}
                {{--]--}}
            {{--});--}}
        {{--});--}}
    {{--</script>--}}
{{--@endsection--}}