routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::post('/test1',['as'=>'etat1','uses'=>'Admin\EtatController@interventionsByEmploye']);
Route::get('/admin/etat/interventions_par_employe','Admin\EtatController@InterByEmpl')->name('admin.interventions_par_employe.index');

Route::post('/test2',['as'=>'etat2','uses'=>'Admin\EtatController@problemesResolus']);
Route::get('/admin/etat/prnr','Admin\EtatController@doc22')->name('admin.prnr.index');

Route::post('/test3',['as'=>'etat3','uses'=>'Admin\EtatController@interventionsByDepartement']);
Route::get('/admin/etat/intervention_par_departement','Admin\EtatController@InterByDept')->name('admin.intervention_par_departement.index');

Route::post('/test4',['as'=>'etat4','uses'=>'Admin\EtatController@interventionsByProbleme']);
Route::get('/admin/etat/interventions_par_problemes','Admin\EtatController@InterByProbleme')->name('admin.interventions_par_problemes.index');

Route::post('/test5',['as'=>'etat5','uses'=>'Admin\EtatController@interventionsByIntervenantByDept']);
Route::get('/admin/etat/intervention_par_intervenant_pour_departement','Admin\EtatController@InterByInterByDept')->name('admin.intervention_par_intervenant_pour_departement.index');

Route::post('/test6',['as'=>'etat6','uses'=>'Admin\EtatController@interventionsByProblemeByDept']);
Route::get('/admin/etat/intervention_par_probleme_departement','Admin\EtatController@InterByProbByDept')->name('admin.intervention_par_probleme_departement.index');

Route::post('/test7',['as'=>'etat7','uses'=>'Admin\EtatController@totaux']);
Route::get('/admin/etat/total_etats','Admin\EtatController@TotalEtat')->name('admin.total_etats.index');

Route::post('/test9',['as'=>'etat9','uses'=>'Admin\EtatController@interventionTotal']);
Route::get('/admin/etat/total_intervention_intervenant','Admin\EtatController@interventionTotal')->name('admin.total_intervention_intervenant.index');


Auth::routes();

//Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
//Route::post('password/reset', 'Auth\PasswordController@reset');


Route::get('/modify', 'HomeController@modify')->name('modify');
Route::post('/modifyValidation', 'HomeController@modifyValidation')->name('modifyValidation');


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/intervention/binder', 'InterventionController@binder');


Route::namespace('Alerte')->group(function (){
   // Route::resource('alerte','Admin\AlerteController');
});


Route::namespace('Admin')->group(function () {

    Route::get('/alerte/alerting', 'AlerteController@alerting');
    Route::post('/alerte/alerting', 'AlerteController@alerting');

    Route::get('/alerte/sendemail', 'AlerteController@sendemail');
    Route::post('/alerte/sendemail', 'AlerteController@sendemail');

    Route::get('/alerte/intervenir', 'AlerteController@intervenir');
    Route::post('/alerte/intervenir', 'AlerteController@intervenir');

    Route::get('/intervenant/pass', 'AlerteController@intervenir');
    Route::post('/intervenant/pass', 'AlerteController@intervenir');

    //Route::get('/admin/modify', 'AdminController@modify')->name('modify');
    //Route::post('/admin/modifyValidation', 'AdminController@modifyValidation')->name('modifyValidation');

    Route::get('/admin/profil','AdminController@index')->name('admin.profil');

    Route::get('/admin/etat/intervenants_par_interventions','EtatController@index')->name('admin.intervenants_par_interventions.index');
    Route::post('/admin/etat/intervenants_par_interventions','EtatController@create')->name('admin.intervenants_par_interventions.create');

    Route::get('/admin/etat/total_etats','TotalController@index')->name('admin.total_etats.index');
    Route::post('/admin/etat/total_etats','TotalController@create')->name('admin.total_etats.create');

    Route::get('/admin/etat','EtatController@create')->name('admin.etat.create');

    Route::get('/interventions/print/{data}',['as'=>'interventions.print','uses'=>'EtatController@print']);

    Route::resource('employe','EmployeController');

    Route::resource('intervenant','IntervenantController');

    Route::resource('intervention','InterventionController');

    Route::resource('probleme','ProblemeController');

    Route::resource('alerte','AlerteController');

    Route::resource('forum','ForumController');
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Employe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employe extends Model
{
    protected $fillable = [
        'nom','prenom','departement'
    ];

    public function agence()
    {
        return $this->belongsTo('App\Agence','agence_id');
    }

    public function departement()
    {
        return $this->belongsTo('App\Departement','departement_id');
    }
}

app/Http/Controllers/Admin/EmployeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Employe;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class EmployeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        $employes = Employe::all();

        return view('admin.employes.index',compact('employes','user'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        return view('admin.employes.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nomEmp'=>'required',
            'prenomEmp'=>'required',
            'agence'=>'required',
            'departement'=>'required'
        ]);

        $e = new Employe();
        $e->nomEmp = strtoupper($request->nomEmp);
        $e->prenomEmp = ucfirst($request->prenomEmp);
        $e->agence_id = $request->agence;
        $e->departement_id = $request->departement;
        $e->save();

        flash('Employe ajouté avec succès');
        return redirect(route('employe.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $employe = Employe::find($id);
        return view('admin.employes.edit',compact('user','employe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nomEmp'=>'required',
            'prenomEmp'=>'required',
            'agence'=>'required',
            'departement'=>'required'
        ]);

        $e = Employe::find($id);
        $e->nomEmp = strtoupper($request->nomEmp);
        $e->prenomEmp = ucfirst($request->prenomEmp);
        $e->agence_id = $request->agence;
        $e->departement_id = $request->departement;
        $e->save();

        flash('Employe modifié avec succès');
        return redirect(route('employe.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/employes/create.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Enrégister un nouvel employé</h3>

        <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('employe.store')}}" method="post">
                {{csrf_field()}}
            <div class="form-group">
                <label>Nom</label>
                <input class="form-control" type="text" name="nomEmp" required value="{{old('nomEmp')}}">
                @if ($errors->has('nomEmp'))
                    <p class="text-danger">{{ $errors->first('nomEmp') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Prénom</label>
                <input class="form-control" type="text" name="prenomEmp" required value="{{old('prenomEmp')}}">
                @if ($errors->has('prenomEmp'))
                    <p class="text-danger">{{ $errors->first('prenomEmp') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Agence</label>
                <select name="agence" id="" class="form-control">
                    <option value="">Sélectionnez une agence</option>
                    @foreach(\App\Agence::all()->sortBy('libelleAgence') as $a)
                        <option value="{{$a->id}}">{{$a->libelleAgence}}</option>
                    @endforeach
                </select>
                @if ($errors->has('agence'))
                    <p class="text-danger">{{ $errors->first('agence') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Département</label>
                <select name="departement" id="" class="form-control">
                    <option value="">Sélectionnez un département</option>
                    @foreach(\App\Departement::all()->sortBy('libelleDept') as $d)
                        <option value="{{$d->id}}">{{$d->libelleDept}}</option>
                    @endforeach
                </select>
                @if ($errors->has('departement'))
                    <p class="text-danger">{{ $errors->first('departement') }}</p>
                @endif
            </div>


            <button type="submit" class="btn btn-primary">Valider</button>
        </form>

    </div>
</div>

@include('layouts.footerAdmin')

resources/views/admin/employes/edit.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center">Modification de l'employé</h3>

        <form class="col-lg-8 col-lg-offset-2 text-center" action="{{route('employe.update',$employe->id)}}" method="post">
            {{csrf_field()}} {{method_field('PUT')}}
            <div class="form-group">
                <label>Nom</label>
                <input class="form-control" type="text" name="nomEmp" required value="{{$employe->nomEmp}}">
                @if ($errors->has('nomEmp'))
                    <p class="text-danger">{{ $errors->first('nomEmp') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Prénom</label>
                <input class="form-control" type="text" name="prenomEmp" required value="{{$employe->prenomEmp}}">
                @if ($errors->has('prenomEmp'))
                    <p class="text-danger">{{ $errors->first('prenomEmp') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Agence</label>
                <select name="agence" id="" class="form-control">
                    <option value="">Sélectionnez une agence</option>
                    @foreach(\App\Agence::all() as $a)
                        <option value="{{$a->id}}">{{$a->libelleAgence}}</option>
                    @endforeach
                </select>
                @if ($errors->has('agence'))
                    <p class="text-danger">{{ $errors->first('agence') }}</p>
                @endif
            </div>

            <div class="form-group">
                <label>Département</label>
                <select name="departement" id="" class="form-control">
                    <option value="">Sélectionnez un département</option>
                    @foreach(\App\Departement::all() as $d)
                        <option value="{{$d->id}}">{{$d->libelleDept}}</option>
                    @endforeach
                </select>
                @if ($errors->has('departement'))
                    <p class="text-danger">{{ $errors->first('departement') }}</p>
                @endif
            </div>

            <a type="button" href="{{route('employe.index')}}" class="btn btn-warning">Annuler</a>

            <button type="submit" class="btn btn-primary">Modifier</button>

        </form>

    </div>
</div>

@include('layouts.footerAdmin')

resources/views/admin/employes/index.blade.php
@include('layouts.headerAdmin')

<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <h2>Liste des employés <a href="{{route('employe.create')}}" class="btn btn-primary pull-right">
                    <i class="zmdi zmdi-plus"></i>
                    Nouvel Employé</a>
            </h2>
            <table class="table table-bordered table-hover tablesorter">
                <thead>
                <tr>
                    <th>Noms <i class="fa fa-sort"></i></th>
                    <th>Prénoms <i class="fa fa-sort"></i></th>
                    <th>Agences <i class="fa fa-sort"></i></th>
                    <th>Départements <i class="fa fa-sort"></i></th>
                </tr>
                </thead>
                <tbody>
                @foreach($employes->sortBy('nomEmp') as $r)
                    <tr>
                        <td>{{$r->nomEmp}}</td>
                        <td>{{$r->prenomEmp}}</td>
                        <td>{{$r->agence->libelleAgence}}</td>
                        <td>{{$r->departement->libelleDept}}</td>
                        <td>
                            <a href="{{route('employe.edit',$r->id)}}">
                                <button class="btn btn-warning" > <i class="zmdi zmdi-edit"></i></button>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>


@include('layouts.footerAdmin')